### ISSUE TITLE
StaticTerminology

### ISSUE THREAD

**Issue by shermanlo77** [aehrc/open-pedigree#7]
Branch: [feature/terminology](https://github.com/aehrc/open-pedigree/tree/feature/terminology)
Affects [PR56 in phenotips:open-pedigree](https://github.com/phenotips/open-pedigree/pull/56)

The use of `StaticTerminology` doesn't work, there may be a bug in the current implementation and for other subclasses of `AbstractTerminology`? If I were to guess, we're not iterating through an array correctly in the method `searchForTerms()`

## Notes

Following the PR from [aehrc:open-pedigree/feature/terminology](https://github.com/aehrc/open-pedigree/tree/feature/terminology) and the [documentation](https://github.com/aehrc/open-pedigree/blob/feature/terminology/terminology.md)

In `app.js`, I've modified the code as instructed

```javascript
  editor = new PedigreeEditor({
    'disorderOptions': {
      'type': 'Static',
      'terms': [
        { 'value': 'HD', 'text': 'Heart Defect' },
        { 'value': 'BN', 'text': 'Big Nose' },
      ]
    }
  });
```

However, when typing at least 2 characters in the disorder field, it brings up the following error

```
StaticTerminology.js:5 Uncaught TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _createForOfIteratorHelper (StaticTerminology.js:5:488)
    at klass.searchForTerms (StaticTerminology.js:86:22)
    at klass.searchForTerms (legend.js:206:23)
    at Selectize.load (nodeMenu.js:198:40)
    at Selectize.<anonymous> (selectize.js:1717:8)
    at Selectize.load (selectize.js:1875:7)
    at Selectize.onSearchChange (selectize.js:1716:9)
    at selectize.js:898:8
_createForOfIteratorHelper @ StaticTerminology.js:5
searchForTerms @ StaticTerminology.js:86
searchForTerms @ legend.js:206
load @ nodeMenu.js:198
(anonymous) @ selectize.js:1717
load @ selectize.js:1875
onSearchChange @ selectize.js:1716
(anonymous) @ selectize.js:898
setTimeout (async)
(anonymous) @ selectize.js:897
onKeyUp @ selectize.js:1696
keyup @ selectize.js:1331
dispatch @ jquery-3.4.1.min.js:2
v.handle @ jquery-3.4.1.min.js:2
```

```
GET http://localhost:9000/resources/icons/xwiki/spinner.gif 404 (Not Found) spinner.gif:1
```

I've tried editing `StaticTerminology.js` to see what happens. I've edited the method

```javascript
  searchForTerms: function (searchTerm, onSuccess, onError, onComplete) {
    let result = ["Heart Defect", "Big Nose"];
    onSuccess(searchTerm, result);
    onComplete();
  }
```

and this produces a different error. This suggests the local variable `foundTerms` isn't iterable and is the cause of the previous error.

The new error message is

```
StaticTerminology.js:77 Uncaught TypeError: onComplete is not a function
    at klass.searchForTerms (StaticTerminology.js:77:5)
    at klass.searchForTerms (legend.js:206:23)
    at Selectize.load (nodeMenu.js:198:40)
    at Selectize.<anonymous> (selectize.js:1717:8)
    at Selectize.load (selectize.js:1875:7)
    at Selectize.onSearchChange (selectize.js:1716:9)
    at selectize.js:898:8
```

Upon inspection, the variable `onComplete` is undefined

The function `searchForTerms()` in `StaticTerminology.js` is called in `legends.js` at

```javascript
  searchForTerms: function(searchTerm, onSuccess, onError, onComplete){
    this._terminology.searchForTerms(searchTerm, onSuccess, onError, onComplete);
  },
```

which is called in `nodeMenu.js` at

```javascript
          load: (query, callback) => {
            if (query.length < 2) return callback();
            editor.getLegend(termType).searchForTerms(query,
              (search, result) => callback(result),
              (err) => callback()
            );
          }
```

Three parameters are provided which suggest `onComplete` is undefined because it isn't provided

**Comment by dconlan** [comment]
Looks like the result from the sifter library is an object and we need to iterate over the searchTerms.items not searchTerms.
I'll add a fix and put a guard on calling onComplete

**Comment by shermanlo77** [comment]
Many thanks!
